### ISSUE TITLE
blacksmith init -- TypeError: Object #<Object> has no method 'help'

### ISSUE THREAD

**Issue by jmonster** [flatiron/blacksmith#40]
jd:Desktop jmonster$ blacksmith init

``` javascript
info: Executing command init
{
  "process": {
    "pid": 17290,
    "uid": 501,
    "gid": 20,
    "cwd": "/Users/jmonster/Desktop",
    "execPath": "/usr/local/Cellar/node/0.6.9/bin/node",
    "version": "v0.6.9",
    "argv": [
      "node",
      "/usr/local/bin/blacksmith",
      "init"
    ],
    "memoryUsage": {
      "rss": 27594752,
      "heapTotal": 17694080,
      "heapUsed": 10891440
    }
  },
  "os": {
    "loadavg": [
      0.421875,
      0.60205078125,
      0.51025390625
    ],
    "uptime": 132447
  },
  "trace": [
    {
      "column": 15,
      "file": "/usr/local/lib/node_modules/blacksmith/lib/commands/init.js",
      "function": "getType",
      "line": 41,
      "method": null,
      "native": false
    },
    {
      "column": 5,
      "file": "/usr/local/lib/node_modules/blacksmith/lib/commands/init.js",
      "function": null,
      "line": 67,
      "method": null,
      "native": false
    },
    {
      "column": 5,
      "file": "/usr/local/lib/node_modules/blacksmith/node_modules/blacksmith-sites/index.js",
      "function": "Object.oncomplete",
      "line": 27,
      "method": "oncomplete",
      "native": false
    }
  ],
  "stack": [
    "TypeError: Object #<Object> has no method 'help'",
    "    at getType (/usr/local/lib/node_modules/blacksmith/lib/commands/init.js:41:15)",
    "    at /usr/local/lib/node_modules/blacksmith/lib/commands/init.js:67:5",
    "    at Object.oncomplete (/usr/local/lib/node_modules/blacksmith/node_modules/blacksmith-sites/index.js:27:5)"
  ],
  "level": "error",
  "message": "uncaughtException"
}
```

**Comment by jherrm** [comment]
I get this same error.  Standard node v0.6.10 installation with homebrew.

**Comment by jfhbrook** [comment]
Hi @jmonster and @jherrm ! I believe this is due to a change in broadway/flatiron that got published last night. I'll look into it.

Edit: In the meantime, you may try to install it by-hand with an older version of flatiron.

**Comment by jfhbrook** [comment]
@jomonster @jherrm **UPDATE:** This was actually an issue with blacksmith trying to use a "help" loglevel in winston. I do not know if this was a mistake on my part, or if winston got refactored. Either way: I just published v0.0.11 and it _should_ work. Please try it and let me know if I'm mistaken!

**Comment by jmonster** [comment]
Success, however now https://github.com/flatiron/blacksmith/issues/41

**Comment by jherrm** [comment]
@jesusabdullah Your update fixed it - thanks!

Although I was initially confused why blacksmith didn't update after running `npm update`, I realized because it was installed globally I had to run `npm update -g`.

**Comment by jfhbrook** [comment]
Great to hear!
