### ISSUE TITLE
blacksmith doesn't work out of the box

### ISSUE THREAD

**Issue by przemoc** [flatiron/blacksmith#48]
System info:

```
przemoc@debian:~$ uname -a
Linux debian 3.2.0-2-amd64 #1 SMP Fri Jun 1 17:49:08 UTC 2012 x86_64 GNU/Linux
przemoc@debian:~$ lsb_release -drc
Description:    Debian GNU/Linux testing (wheezy)
Release:    testing
Codename:   wheezy
przemoc@debian:~$ nodejs --version
v0.6.19
```

blacksmith installation:

```
przemoc@debian:~$ sudo npm install blacksmith -g
[sudo] password for przemoc: 
npm http GET https://registry.npmjs.org/blacksmith
npm http 200 https://registry.npmjs.org/blacksmith
npm http GET https://registry.npmjs.org/blacksmith/-/blacksmith-0.0.11.tgz
npm http GET https://registry.npmjs.org/blacksmith-sites
npm http GET https://registry.npmjs.org/marked
npm http GET https://registry.npmjs.org/traverse
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/http-server/0.2.4
npm http GET https://registry.npmjs.org/jsdom
npm http GET https://registry.npmjs.org/weld/0.2.1
npm http GET https://registry.npmjs.org/findit
npm http GET https://registry.npmjs.org/flatiron/0.1.5-1
npm http GET https://registry.npmjs.org/nconf/0.4.3
npm http GET https://registry.npmjs.org/ncp
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/rss
npm http GET https://registry.npmjs.org/hashish
npm http GET https://registry.npmjs.org/prompt
npm http GET https://registry.npmjs.org/winston
npm http GET https://registry.npmjs.org/cliff
npm http GET https://registry.npmjs.org/utile/0.0.10
npm http GET https://registry.npmjs.org/alists
npm http GET https://registry.npmjs.org/async
npm http 200 https://registry.npmjs.org/http-server/0.2.4
npm http GET https://registry.npmjs.org/http-server/-/http-server-0.2.4.tgz
npm http 200 https://registry.npmjs.org/blacksmith-sites
npm http GET https://registry.npmjs.org/blacksmith-sites/-/blacksmith-sites-0.0.3.tgz
npm http 200 https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/mkdirp/-/mkdirp-0.0.7.tgz
npm http 200 https://registry.npmjs.org/weld/0.2.1
npm http GET https://registry.npmjs.org/weld/-/weld-0.2.1.tgz
npm http 200 https://registry.npmjs.org/traverse
npm http GET https://registry.npmjs.org/traverse/-/traverse-0.4.6.tgz
npm http 200 https://registry.npmjs.org/flatiron/0.1.5-1
npm http GET https://registry.npmjs.org/flatiron/-/flatiron-0.1.5-1.tgz
npm http 200 https://registry.npmjs.org/findit
npm http GET https://registry.npmjs.org/findit/-/findit-0.1.2.tgz
npm http 200 https://registry.npmjs.org/nconf/0.4.3
npm http GET https://registry.npmjs.org/nconf/-/nconf-0.4.3.tgz
npm http 200 https://registry.npmjs.org/marked
npm http GET https://registry.npmjs.org/marked/-/marked-0.1.9.tgz
npm http 200 https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/colors/-/colors-0.6.0-1.tgz
npm http 200 https://registry.npmjs.org/ncp
npm http 200 https://registry.npmjs.org/jsdom
npm http GET https://registry.npmjs.org/ncp/-/ncp-0.2.6.tgz
npm http GET https://registry.npmjs.org/jsdom/-/jsdom-0.2.14.tgz
npm http 200 https://registry.npmjs.org/optimist
npm http 200 https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/optimist/-/optimist-0.2.8.tgz
npm http 200 https://registry.npmjs.org/rss
npm http GET https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.2.tgz
npm http GET https://registry.npmjs.org/rss/-/rss-0.0.3.tgz
npm http 200 https://registry.npmjs.org/hashish
npm http 200 https://registry.npmjs.org/prompt
npm http GET https://registry.npmjs.org/hashish/-/hashish-0.0.4.tgz
npm http GET https://registry.npmjs.org/prompt/-/prompt-0.1.12.tgz
npm http 200 https://registry.npmjs.org/utile/0.0.10
npm http GET https://registry.npmjs.org/utile/-/utile-0.0.10.tgz
npm http 200 https://registry.npmjs.org/cliff
npm http GET https://registry.npmjs.org/cliff/-/cliff-0.1.8.tgz
npm http 200 https://registry.npmjs.org/alists
npm http GET https://registry.npmjs.org/alists/-/alists-0.0.2.tgz
npm http 200 https://registry.npmjs.org/winston
npm http GET https://registry.npmjs.org/winston/-/winston-0.5.11.tgz
npm http 200 https://registry.npmjs.org/async
npm WARN excluding symbolic link test/symlinks/dir1/dangling-symlink -> does-not-exist
npm WARN package.json weld@0.2.1 'contributers' should probably be 'contributors'
npm http GET https://registry.npmjs.org/seq
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/xml
npm http GET https://registry.npmjs.org/logging
npm http GET https://registry.npmjs.org/director/1.0.8
npm http GET https://registry.npmjs.org/pkginfo/0.2.2
npm http GET https://registry.npmjs.org/broadway/0.1.4
npm http GET https://registry.npmjs.org/prompt/0.1.11
npm http GET https://registry.npmjs.org/pkginfo
npm http GET https://registry.npmjs.org/eyes
npm http GET https://registry.npmjs.org/winston
npm http GET https://registry.npmjs.org/ini
npm http GET https://registry.npmjs.org/pkginfo
npm http GET https://registry.npmjs.org/loggly
npm http GET https://registry.npmjs.org/stack-trace
npm http GET https://registry.npmjs.org/htmlparser
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/cssom
npm http GET https://registry.npmjs.org/contextify
npm http 200 https://registry.npmjs.org/director/1.0.8
npm http GET https://registry.npmjs.org/director/-/director-1.0.8.tgz
npm http 200 https://registry.npmjs.org/xml
npm http GET https://registry.npmjs.org/xml/-/xml-0.0.7.tgz
npm http 200 https://registry.npmjs.org/pkginfo/0.2.2
npm http GET https://registry.npmjs.org/pkginfo/-/pkginfo-0.2.2.tgz
npm http 200 https://registry.npmjs.org/rimraf
npm http 200 https://registry.npmjs.org/logging
npm http GET https://registry.npmjs.org/rimraf/-/rimraf-1.0.9.tgz
npm http GET https://registry.npmjs.org/logging/-/logging-2.0.16.tgz
npm http 200 https://registry.npmjs.org/broadway/0.1.4
npm http GET https://registry.npmjs.org/broadway/-/broadway-0.1.4.tgz
npm http 200 https://registry.npmjs.org/prompt/0.1.11
npm http GET https://registry.npmjs.org/prompt/-/prompt-0.1.11.tgz
npm http 200 https://registry.npmjs.org/seq
npm http GET https://registry.npmjs.org/seq/-/seq-0.3.5.tgz
npm http 304 https://registry.npmjs.org/winston
npm http GET https://registry.npmjs.org/winston/-/winston-0.6.1.tgz
npm http 200 https://registry.npmjs.org/pkginfo
npm http GET https://registry.npmjs.org/pkginfo/-/pkginfo-0.2.3.tgz
npm http 200 https://registry.npmjs.org/eyes
npm http GET https://registry.npmjs.org/eyes/-/eyes-0.1.7.tgz
npm http 200 https://registry.npmjs.org/ini
npm http GET https://registry.npmjs.org/ini/-/ini-1.0.2.tgz
npm http 200 https://registry.npmjs.org/pkginfo
npm http 200 https://registry.npmjs.org/stack-trace
npm http GET https://registry.npmjs.org/stack-trace/-/stack-trace-0.0.6.tgz
npm http 200 https://registry.npmjs.org/loggly
npm http GET https://registry.npmjs.org/loggly/-/loggly-0.3.11.tgz
npm http 200 https://registry.npmjs.org/cssom
npm http GET https://registry.npmjs.org/cssom/-/cssom-0.2.3.tgz
npm http 200 https://registry.npmjs.org/htmlparser
npm http GET https://registry.npmjs.org/htmlparser/-/htmlparser-1.7.6.tgz
npm http 200 https://registry.npmjs.org/contextify
npm http GET https://registry.npmjs.org/contextify/-/contextify-0.1.3.tgz
npm http 200 https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/request/-/request-2.9.202.tgz
npm http GET https://registry.npmjs.org/chainsaw
npm http GET https://registry.npmjs.org/eventemitter2/0.4.1
npm http GET https://registry.npmjs.org/nconf/0.5.0
npm http GET https://registry.npmjs.org/winston/0.5.9
npm http GET https://registry.npmjs.org/utile/0.0.9
npm http GET https://registry.npmjs.org/cycle
npm http GET https://registry.npmjs.org/pkginfo
npm http GET https://registry.npmjs.org/request
npm http 200 https://registry.npmjs.org/chainsaw
npm http GET https://registry.npmjs.org/chainsaw/-/chainsaw-0.0.9.tgz
npm http GET https://registry.npmjs.org/timespan
npm http 200 https://registry.npmjs.org/utile/0.0.9
npm http GET https://registry.npmjs.org/utile/-/utile-0.0.9.tgz
npm http 200 https://registry.npmjs.org/cycle
npm http GET https://registry.npmjs.org/cycle/-/cycle-1.0.0.tgz
npm http 304 https://registry.npmjs.org/pkginfo
npm http 200 https://registry.npmjs.org/nconf/0.5.0
npm http GET https://registry.npmjs.org/nconf/-/nconf-0.5.0.tgz
npm http 304 https://registry.npmjs.org/request
npm http 200 https://registry.npmjs.org/eventemitter2/0.4.1
npm http GET https://registry.npmjs.org/eventemitter2/-/eventemitter2-0.4.1.tgz
npm http 200 https://registry.npmjs.org/timespan
npm http GET https://registry.npmjs.org/timespan/-/timespan-2.2.0.tgz
npm http 200 https://registry.npmjs.org/winston/0.5.9
npm http GET https://registry.npmjs.org/winston/-/winston-0.5.9.tgz
npm http GET https://registry.npmjs.org/traverse
npm WARN package.json eventemitter2@0.4.1 'contributers' should probably be 'contributors'
npm http 304 https://registry.npmjs.org/traverse
npm http GET https://registry.npmjs.org/traverse/-/traverse-0.3.9.tgz
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/ini
npm http GET https://registry.npmjs.org/eyes
npm http GET https://registry.npmjs.org/loggly
npm http GET https://registry.npmjs.org/stack-trace
npm http 304 https://registry.npmjs.org/loggly
npm http 304 https://registry.npmjs.org/stack-trace
npm http 200 https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/bindings/-/bindings-0.3.0.tgz
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/ini
npm http 304 https://registry.npmjs.org/eyes
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/timespan

> contextify@0.1.3 install /usr/lib/node_modules/blacksmith/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

npm http 304 https://registry.npmjs.org/timespan
npm http 304 https://registry.npmjs.org/request
gyp WARN install got an error, rolling back install
gyp ERR! rebuild error Error: EACCES, stat '/root/.node-gyp/0.6.19'
gyp ERR! not ok 
npm WARN optional dep failed, continuing contextify@0.1.3
/usr/bin/blacksmith -> /usr/lib/node_modules/blacksmith/bin/blacksmith
alists@0.0.2 /usr/lib/node_modules/blacksmith/node_modules/alists

colors@0.6.0-1 /usr/lib/node_modules/blacksmith/node_modules/colors

hashish@0.0.4 /usr/lib/node_modules/blacksmith/node_modules/hashish

mkdirp@0.0.7 /usr/lib/node_modules/blacksmith/node_modules/mkdirp

weld@0.2.1 /usr/lib/node_modules/blacksmith/node_modules/weld

marked@0.1.9 /usr/lib/node_modules/blacksmith/node_modules/marked

wordwrap@0.0.2 /usr/lib/node_modules/blacksmith/node_modules/wordwrap

async@0.1.22 /usr/lib/node_modules/blacksmith/node_modules/async

ncp@0.2.6 /usr/lib/node_modules/blacksmith/node_modules/ncp

optimist@0.2.8 /usr/lib/node_modules/blacksmith/node_modules/optimist

traverse@0.4.6 /usr/lib/node_modules/blacksmith/node_modules/traverse

http-server@0.2.4 /usr/lib/node_modules/blacksmith/node_modules/http-server

blacksmith-sites@0.0.3 /usr/lib/node_modules/blacksmith/node_modules/blacksmith-sites

rimraf@1.0.9 /usr/lib/node_modules/blacksmith/node_modules/utile/node_modules/rimraf

utile@0.0.10 /usr/lib/node_modules/blacksmith/node_modules/utile

logging@2.0.16 /usr/lib/node_modules/blacksmith/node_modules/rss/node_modules/logging

xml@0.0.7 /usr/lib/node_modules/blacksmith/node_modules/rss/node_modules/xml

rss@0.0.3 /usr/lib/node_modules/blacksmith/node_modules/rss

pkginfo@0.2.3 /usr/lib/node_modules/blacksmith/node_modules/prompt/node_modules/pkginfo

prompt@0.1.12 /usr/lib/node_modules/blacksmith/node_modules/prompt

ini@1.0.2 /usr/lib/node_modules/blacksmith/node_modules/nconf/node_modules/ini

pkginfo@0.2.3 /usr/lib/node_modules/blacksmith/node_modules/nconf/node_modules/pkginfo

nconf@0.4.3 /usr/lib/node_modules/blacksmith/node_modules/nconf

eyes@0.1.7 /usr/lib/node_modules/blacksmith/node_modules/cliff/node_modules/eyes

cycle@1.0.0 /usr/lib/node_modules/blacksmith/node_modules/cliff/node_modules/winston/node_modules/cycle

stack-trace@0.0.6 /usr/lib/node_modules/blacksmith/node_modules/cliff/node_modules/winston/node_modules/stack-trace

pkginfo@0.2.3 /usr/lib/node_modules/blacksmith/node_modules/cliff/node_modules/winston/node_modules/pkginfo

request@2.9.202 /usr/lib/node_modules/blacksmith/node_modules/cliff/node_modules/winston/node_modules/request

winston@0.6.1 /usr/lib/node_modules/blacksmith/node_modules/cliff/node_modules/winston

cliff@0.1.8 /usr/lib/node_modules/blacksmith/node_modules/cliff

eyes@0.1.7 /usr/lib/node_modules/blacksmith/node_modules/winston/node_modules/eyes

stack-trace@0.0.6 /usr/lib/node_modules/blacksmith/node_modules/winston/node_modules/stack-trace

pkginfo@0.2.3 /usr/lib/node_modules/blacksmith/node_modules/winston/node_modules/pkginfo

timespan@2.2.0 /usr/lib/node_modules/blacksmith/node_modules/winston/node_modules/loggly/node_modules/timespan

request@2.9.202 /usr/lib/node_modules/blacksmith/node_modules/winston/node_modules/loggly/node_modules/request

loggly@0.3.11 /usr/lib/node_modules/blacksmith/node_modules/winston/node_modules/loggly

winston@0.5.11 /usr/lib/node_modules/blacksmith/node_modules/winston

traverse@0.3.9 /usr/lib/node_modules/blacksmith/node_modules/findit/node_modules/seq/node_modules/chainsaw/node_modules/traverse

chainsaw@0.0.9 /usr/lib/node_modules/blacksmith/node_modules/findit/node_modules/seq/node_modules/chainsaw

seq@0.3.5 /usr/lib/node_modules/blacksmith/node_modules/findit/node_modules/seq

findit@0.1.2 /usr/lib/node_modules/blacksmith/node_modules/findit

pkginfo@0.2.2 /usr/lib/node_modules/blacksmith/node_modules/flatiron/node_modules/pkginfo

prompt@0.1.11 /usr/lib/node_modules/blacksmith/node_modules/flatiron/node_modules/prompt

director@1.0.8 /usr/lib/node_modules/blacksmith/node_modules/flatiron/node_modules/director

eventemitter2@0.4.1 /usr/lib/node_modules/blacksmith/node_modules/flatiron/node_modules/broadway/node_modules/eventemitter2

rimraf@1.0.9 /usr/lib/node_modules/blacksmith/node_modules/flatiron/node_modules/broadway/node_modules/utile/node_modules/rimraf

utile@0.0.9 /usr/lib/node_modules/blacksmith/node_modules/flatiron/node_modules/broadway/node_modules/utile

ini@1.0.2 /usr/lib/node_modules/blacksmith/node_modules/flatiron/node_modules/broadway/node_modules/nconf/node_modules/ini

nconf@0.5.0 /usr/lib/node_modules/blacksmith/node_modules/flatiron/node_modules/broadway/node_modules/nconf

eyes@0.1.7 /usr/lib/node_modules/blacksmith/node_modules/flatiron/node_modules/broadway/node_modules/winston/node_modules/eyes

stack-trace@0.0.6 /usr/lib/node_modules/blacksmith/node_modules/flatiron/node_modules/broadway/node_modules/winston/node_modules/stack-trace

timespan@2.2.0 /usr/lib/node_modules/blacksmith/node_modules/flatiron/node_modules/broadway/node_modules/winston/node_modules/loggly/node_modules/timespan

request@2.9.202 /usr/lib/node_modules/blacksmith/node_modules/flatiron/node_modules/broadway/node_modules/winston/node_modules/loggly/node_modules/request

loggly@0.3.11 /usr/lib/node_modules/blacksmith/node_modules/flatiron/node_modules/broadway/node_modules/winston/node_modules/loggly

winston@0.5.9 /usr/lib/node_modules/blacksmith/node_modules/flatiron/node_modules/broadway/node_modules/winston

broadway@0.1.4 /usr/lib/node_modules/blacksmith/node_modules/flatiron/node_modules/broadway

flatiron@0.1.5-1 /usr/lib/node_modules/blacksmith/node_modules/flatiron

cssom@0.2.3 /usr/lib/node_modules/blacksmith/node_modules/jsdom/node_modules/cssom

request@2.9.202 /usr/lib/node_modules/blacksmith/node_modules/jsdom/node_modules/request

htmlparser@1.7.6 /usr/lib/node_modules/blacksmith/node_modules/jsdom/node_modules/htmlparser

jsdom@0.2.14 /usr/lib/node_modules/blacksmith/node_modules/jsdom
```

Blog creation:

```
przemoc@debian:~$ blacksmith init
info: Executing command init
info: init can create any of these site types:
info: 
info:     * doc: A docs site for blacksmith
info:     * blog: A simple blacksmith blog using Scribbish
info: 
prompt: Choose your website type: blog
info: Selecting website type blog...
prompt: Name your website: blog
warn: blacksmith is about to write a blog site to ./blog!
prompt: Is this okay? [y/N]: y
info: * Created `./blog`.
```

Generation:

```
przemoc@debian:~$ cd blog/
przemoc@debian:~/blog$ blacksmith generate
info: Executing command generate
{
  "process": {
    "pid": 5516,
    "uid": 1000,
    "gid": 1000,
    "cwd": "/home/przemoc/blog",
    "execPath": "/usr/bin/node",
    "version": "v0.6.19",
    "argv": [
      "node",
      "/usr/bin/blacksmith",
      "generate"
    ],
    "memoryUsage": {
      "rss": 32608256,
      "heapTotal": 30156288,
      "heapUsed": 13121912
    }
  },
  "os": {
    "loadavg": [
      0.98583984375,
      1.05078125,
      1.06005859375
    ],
    "uptime": 3726.38355848
  },
  "trace": [
    {
      "column": 59,
      "file": "/usr/lib/node_modules/blacksmith/node_modules/jsdom/lib/jsdom.js",
      "function": null,
      "line": 171,
      "method": null,
      "native": false
    },
    {
      "column": 5,
      "file": "/usr/lib/node_modules/blacksmith/node_modules/jsdom/lib/jsdom.js",
      "function": "Object.env",
      "line": 262,
      "method": "env",
      "native": false
    },
    {
      "column": 9,
      "file": "/usr/lib/node_modules/blacksmith/lib/blacksmith.js",
      "function": "Object.generate",
      "line": 83,
      "method": "generate",
      "native": false
    },
    {
      "column": 11,
      "file": "/usr/lib/node_modules/blacksmith/lib/commands/generate.js",
      "function": null,
      "line": 22,
      "method": null,
      "native": false
    },
    {
      "column": 19,
      "file": "/usr/lib/node_modules/blacksmith/node_modules/flatiron/lib/flatiron/plugins/cli.js",
      "function": "executeCommand",
      "line": 176,
      "method": null,
      "native": false
    },
    {
      "column": 5,
      "file": "/usr/lib/node_modules/blacksmith/node_modules/flatiron/lib/flatiron/plugins/cli.js",
      "function": "",
      "line": 221,
      "method": null,
      "native": false
    },
    {
      "column": 21,
      "file": "Object].dispatch (/usr/lib/node_modules/blacksmith/node_modules/flatiron/node_modules/director/lib/director/cli.js",
      "function": "[object",
      "line": 50,
      "method": null,
      "native": false
    },
    {
      "column": 18,
      "file": "/usr/lib/node_modules/blacksmith/node_modules/flatiron/lib/flatiron/plugins/cli.js",
      "function": null,
      "line": 58,
      "method": null,
      "native": false
    },
    {
      "column": 12,
      "file": "Object].<anonymous> (/usr/lib/node_modules/blacksmith/node_modules/flatiron/node_modules/broadway/lib/broadway/app.js",
      "function": "[object",
      "line": 74,
      "method": null,
      "native": false
    },
    {
      "column": 31,
      "file": "Object].init (/usr/lib/node_modules/blacksmith/node_modules/flatiron/lib/flatiron/app.js",
      "function": "[object",
      "line": 31,
      "method": null,
      "native": false
    }
  ],
  "stack": [
    "TypeError: Cannot read property 'implementation' of undefined",
    "    at /usr/lib/node_modules/blacksmith/node_modules/jsdom/lib/jsdom.js:171:59",
    "    at Object.env (/usr/lib/node_modules/blacksmith/node_modules/jsdom/lib/jsdom.js:262:5)",
    "    at Object.generate (/usr/lib/node_modules/blacksmith/lib/blacksmith.js:83:9)",
    "    at /usr/lib/node_modules/blacksmith/lib/commands/generate.js:22:11",
    "    at executeCommand (/usr/lib/node_modules/blacksmith/node_modules/flatiron/lib/flatiron/plugins/cli.js:176:19)",
    "    at Object.<anonymous> (/usr/lib/node_modules/blacksmith/node_modules/flatiron/lib/flatiron/plugins/cli.js:221:5)",
    "    at [object Object].dispatch (/usr/lib/node_modules/blacksmith/node_modules/flatiron/node_modules/director/lib/director/cli.js:50:21)",
    "    at /usr/lib/node_modules/blacksmith/node_modules/flatiron/lib/flatiron/plugins/cli.js:58:18",
    "    at [object Object].<anonymous> (/usr/lib/node_modules/blacksmith/node_modules/flatiron/node_modules/broadway/lib/broadway/app.js:74:12)",
    "    at [object Object].init (/usr/lib/node_modules/blacksmith/node_modules/flatiron/lib/flatiron/app.js:31:31)"
  ],
  "level": "error",
  "message": "uncaughtException"
}
```

Did I forget about something?

**Comment by jfhbrook** [comment]
This appears to be an issue directly related to spawning a jsdom env. @tmpvar Does this error mean anything to you?

**Comment by aus** [comment]
I experienced the same issue. Here is what I did to resolve:

``` bash
npm uninstall blacksmith -g
apt-get install g++ 
npm install blacksmith -g
```

jsdom needs the g++ packages to compile correctly, it would seem. Strange that it doesn't note this with `npm install blacksmith -g`

**Comment by przemoc** [comment]
@aus, are you sure that you experienced the same issue?

`g++` is one of the last things that my system would ever lack.

**Comment by aus** [comment]
@przemoc I attempted to recreate the issue as closely as possible. Unfortunately, I couldn't recreate it. Here is what I did:
1. First, I fired up a new, fresh AWS instance using Ubuntu Server 12.01 LTS.
2. `sudo apt-get install nodejs npm`
3. `sudo npm install -g blacksmith`
4. Install fails saying we need g++ so `sudo apt-get install g++`
5. `sudo npm install -g blacksmith` again
6. No errors this time. Only a few misc warnings.
7. `blacksmith init`

Maybe try reinstalling blacksmith with `npm uninstall -g blacksmith` then `npm install -g blacksmith`?

```
ubuntu@domU-12-31-39-02-E9-D5:~$ uname -a
Linux domU-12-31-39-02-E9-D5 3.2.0-25-virtual #40-Ubuntu SMP 
Wed May 23 22:20:17 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@domU-12-31-39-02-E9-D5:~$ node --version                                
v0.6.12
```

**Comment by przemoc** [comment]
@aus, `blacksmith init` works (well, there is a gyp error, but on an optional dependency).
It's `blacksmith generate` that fails, as you can see in my listing. (And I tried reinstalling, but it doesn't change a thing - I have `g++` since the beginning.)
So, does the _last generation step_ work for you? And if yes, you still use different distribution with different nodejs version and packaging, so I don't know, it may be relevant to the issue.

@tmpvar, @jesusabdullah asked you before whether the error means anything to you. I would like to raise this question again, in case you missed that.

**Comment by jfhbrook** [comment]
All I get out of the error is that jsdom failed to install properly, and hard. @tmpvar is your best bet in terms of finding out why.

**Comment by tmpvar** [comment]
that error looks like contextify not being installed.  What version of python are you running?

**Comment by przemoc** [comment]
```
$ python --version
Python 2.7.3rc2
```

EDIT: So it's not optional after all?

**Comment by tmpvar** [comment]
looks like the problem here is the mix between sudo/npm.  running the command `npm install -g blacksmith` as root worked with great success.

**Comment by przemoc** [comment]
Knowing @tmpvar is not-afk atm, I've pinged him on IRC and we quickly found the solution. Thanks, Elijah!
