### ISSUE TITLE
Issue generating blacksmith site.

### ISSUE THREAD

**Issue by phillyger** [flatiron/blacksmith#69]
Seeing the following error when attempting to generate a new <code>blacksmith</code> site using latest release <code>1.1.0</code>.

<code>/usr/local/lib/node_modules/blacksmith/node_modules/async/lib/async.js:81
        if (!arr.length) {
                ^
TypeError: Cannot read property 'length' of undefined
    at Object.async.forEach (/usr/local/lib/node_modules/blacksmith/node_modules/async/lib/async.js:81:17)
    at common.readAll (/usr/local/lib/node_modules/blacksmith/lib/blacksmith/common.js:69:11)
    at Object.oncomplete (fs.js:297:15)</code>

**Comment by gorsti** [comment]
Getting the same error, didn't have any probem with npm install of Jitsu (un-related to this issue) on same machine, however blacksmith is showing - happy to help debug, taking a look at async.js now

Rendering: /users/gordonsuttie/blacksmith/
Error rendering: /users/gordonsuttie/blacksmith/
{ [Error: ENOENT, open '/users/gordonsuttie/blacksmith/.blacksmith']
  errno: 34,
  code: 'ENOENT',
  path: '/users/gordonsuttie/blacksmith/.blacksmith' }
[ 'Error: ENOENT, open \'/users/gordonsuttie/blacksmith/.blacksmith\'' ]

/usr/local/share/npm/lib/node_modules/blacksmith/node_modules/async/lib/async.js:81
        if (!arr.length) {
                ^
TypeError: Cannot read property 'length' of undefined
    at Object.async.forEach (/usr/local/share/npm/lib/node_modules/blacksmith/node_modules/async/lib/async.js:81:17)
    at common.readAll (/usr/local/share/npm/lib/node_modules/blacksmith/lib/blacksmith/common.js:69:11)
    at Object.oncomplete (fs.js:297:15)

**Comment by indexzero** [comment]
You don't have a `.blacksmith` file. Add one and it will work

Please read the blog post about how there is **zero backwards compatibility with blacksmith pre-1.0**: http://blog.flatironjs.org/01-a-whole-new-blacksmith
