### ISSUE TITLE
fails when running in non blacksmith directory

### ISSUE THREAD

**Issue by venil7** [flatiron/blacksmith#73]
D:!>blacksmith
Rendering: D:!
Error rendering: D:!
{ [Error: ENOENT, open 'D:!.blacksmith'] errno: 34, code: 'ENOENT', path: 'D:\!\.blacksmith' }
[ 'Error: ENOENT, open \'D:\!\.blacksmith\'' ]

C:\Users\user\AppData\Roaming\npm\node_modules\blacksmith\node_modules\async\lib\async.js:81
        if (!arr.length) {
                ^
TypeError: Cannot read property 'length' of undefined
    at Object.async.forEach (C:\Users\user\AppData\Roaming\npm\node_modules\blacksmith\node_modules\async\lib\async.js:81:17)
    at common.readAll (C:\Users\user\AppData\Roaming\npm\node_modules\blacksmith\lib\blacksmith\common.js:69:11)
    at Object.oncomplete (fs.js:297:15)

**Comment by blakmatrix** [comment]
@venil7 do you actually have a correct layout created ? try downloading https://github.com/nodejitsu/handbook and cd into that repo and run blacksmith.

**Comment by venil7** [comment]
should it not fail a bit more gracefully? an error message?
