### ISSUE TITLE
npm package broken

### ISSUE THREAD

**Issue by silverbucket** [flatiron/blacksmith#99]
I installed blacksmith as described:

`$ sudo npm install blacksmith -g`

However when I run it I get errors:

```
$ blacksmith
Rendering: /home/nkj/code
Error rendering: /home/nkj/code
{ [Error: ENOENT, open '/home/nkj/code/.blacksmith'] errno: 34, code: 'ENOENT', path: '/home/nkj/code/.blacksmith' }
[ 'Error: ENOENT, open \'/home/nkj/code/.blacksmith\'' ]

/usr/lib/node_modules/blacksmith/node_modules/async/lib/async.js:81
        if (!arr.length) {
                ^
TypeError: Cannot read property 'length' of undefined
    at Object.async.forEach (/usr/lib/node_modules/blacksmith/node_modules/async/lib/async.js:81:17)
    at /usr/lib/node_modules/blacksmith/lib/blacksmith/common.js:69:11
    at Object.oncomplete (fs.js:107:15)
```

**Comment by fiatjaf** [comment]
The same here.

**Comment by fiatjaf** [comment]
It is not just the npm package. Building from source gives me the same.

But the problem happens only because you don't have a structured blacksmith directory (with content, layouts and the .blacksmith file).

**Comment by howarddierking** [comment]
+1

**Comment by DanielSundberg** [comment]
I get the same error message, are there no development done in this project?

According to the documentation this project would have suited my documentation needs but I can't get it to run? Any recommendations on what to use instead with a similar feature set? 
.

**Comment by fiatjaf** [comment]
@DanielSundberg This is abandoned, but perhaps you will find what you want in [these forks](https://github.com/flatiron/blacksmith/network).

**Comment by bretonio** [comment]
Likewise.

``` sh
Rendering: blacksmithy
Error rendering: blacksmithy
{ [Error: ENOENT, open 'blacksmithy/.blacksmith'] errno: -2, code: 'ENOENT', path: 'blacksmithy/.blacksmith' }
[ 'Error: ENOENT, open \'blacksmithy/.blacksmith\'',
  '    at Error (native)' ]
```

Will  check the forks.
